version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=app.py
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0